# Copyright (c) Forward Email LLC
# SPDX-License-Identifier: BUSL-1.1

---
all:
  children:
    bree:
      hosts:
        bree-vu-sj-ca:
          ansible_host: 0.0.0.0
    http:
      children:
        web:
          hosts:
            web-do-sf-ca:
              ansible_host: 0.0.0.0
            web-vu-sj-ca:
              ansible_host: 0.0.0.0
        api:
          hosts:
            api-do-sf-ca:
              ansible_host: 0.0.0.0
            api-vu-sj-ca:
              ansible_host: 0.0.0.0
    smtp:
      hosts:
        smtp-vu-sj-ca:
          ansible_host: 0.0.0.0
        smtp-do-am-nl:
          ansible_host: 0.0.0.0
    imap:
      hosts:
        imap-vu-sj-ca:
          ansible_host: 0.0.0.0
        imap-do-am-nl:
          ansible_host: 0.0.0.0
    pop3:
      hosts:
        pop3-vu-sj-ca:
          ansible_host: 0.0.0.0
    sqlite:
      hosts:
        sqlite-do-sf-ca:
          ansible_host: 0.0.0.0
