# Copyright (c) Forward Email LLC
# SPDX-License-Identifier: BUSL-1.1

---
- hosts: all
  name: Certificates
  vars_prompt:
    - name: input_key
      prompt: Enter path to certificate private key file (e.g. /path/to/.ssl-key)
      private: false
    - name: input_cert
      prompt: Enter path to certificate full chain/certificate file (e.g. /path/to/.ssl-cert)
      private: false
    - name: input_bundle
      prompt: "Optional: Leave blank or enter path to certificate CA bundle file (e.g. /path/to/.ssl-ca)"
      private: false
    - name: input_apple_key
      prompt: "Optional: Leave blank or enter path to Apple K8 certificate key file (e.g. /path/to/AuthKey_00000000000.p8)"
      private: false

  tasks:
    # key file
    - name: Check if key file exists
      local_action: stat path={{ input_key }}
      become: false
      register: local_key_file
    - name: Fail when local key file does not exist
      fail:
        msg: "key file does not exist: {{ input_key }}"
      when: not local_key_file.stat.exists

    # cert file
    - name: Check if cert file exists
      local_action: stat path={{ input_cert }}
      become: false
      register: local_cert_file

    - name: Fail when local cert file does not exist
      fail:
        msg: "cert file does not exist: {{ input_cert }}"
      when: not local_cert_file.stat.exists

    # bundle file
    - name: Check if bundle file exists
      local_action: stat path={{ input_bundle }}
      register: local_bundle_file
      become: false
      when: (input_bundle is defined) and (input_bundle | length > 0)

    - name: Fail when local bundle file does not exist
      fail:
        msg: "bundle file does not exist: {{ input_bundle }}"
      when: (input_bundle is defined) and (input_bundle | length > 0) and (not local_bundle_file.stat.exists)

    # apple_key file
    - name: Check if apple_key file exists
      local_action: stat path={{ input_apple_key }}
      register: local_apple_key_file
      become: false
      when: (input_apple_key is defined) and (input_apple_key | length > 0)

    - name: Fail when local apple_key file does not exist
      fail:
        msg: "apple_key file does not exist: {{ input_apple_key }}"
      when: (input_apple_key is defined) and (input_apple_key | length > 0) and (not local_apple_key_file.stat.exists)

    # remote dir
    - name: Check if remote dir exists
      stat:
        path: /var/www/production
      register: remote_dir

    - name: Fail when remote dir does not exist
      fail:
        msg: pm2 dir not yet created
      when: not remote_dir.stat.exists or not remote_dir.stat.isdir

    # copy local key
    - name: Copy local key file to server
      copy:
        src: "{{ input_key }}"
        dest: /var/www/production/.ssl-key
        owner: deploy
        # https://chmodcommand.com/chmod-660/
        mode: "0660"

    # copy local cert
    - name: Copy local cert file to server
      copy:
        src: "{{ input_cert }}"
        dest: /var/www/production/.ssl-cert
        owner: deploy
        # https://chmodcommand.com/chmod-660/
        mode: "0660"

    # copy local bundle
    - name: Copy local bundle file to server
      copy:
        src: "{{ input_bundle }}"
        dest: /var/www/production/.ssl-ca
        owner: deploy
        # https://chmodcommand.com/chmod-660/
        mode: "0660"
      when: (input_bundle is defined) and (input_bundle | length > 0)

    # copy local apple_key
    - name: Copy local apple_key file to server
      copy:
        src: "{{ input_apple_key }}"
        dest: "/var/www/production/{{ input_apple_key | basename }}"
        owner: deploy
        # https://chmodcommand.com/chmod-660/
        mode: "0660"
      when: (input_apple_key is defined) and (input_apple_key | length > 0)
