# Copyright (c) Forward Email LLC
# SPDX-License-Identifier: BUSL-1.1

---
# Ansible Collections
collections:
  - name: ansible.posix
    version: "2.1.0"
  - name: community.general
    version: "12.0.1"
  - name: hifis.toolkit
    version: "6.2.2"

# Ansible Roles
roles:
  - name: dns
    src: oefenweb.dns
    version: v1.1.41
  - name: fail2ban
    src: oefenweb.fail2ban
    version: v4.0.11
  - name: sysctl
    src: oefenweb.sysctl
    version: v1.0.44
