# Copyright (c) Forward Email LLC
# SPDX-License-Identifier: BUSL-1.1

---
- name: swapfile
  src: oefenweb.swapfile
  version: v2.0.37
- name: dns
  src: oefenweb.dns
  version: v1.1.36
- name: ntp
  src: oefenweb.ntp
  version: v1.1.35
- name: fail2ban
  src: oefenweb.fail2ban
  version: v4.0.2
#- name: timezone
#  src: oefenweb.timezone
#  version: v1.0.50
- name: unattended-upgrades
  src: hifis.unattended_upgrades
  version: v2.0.1
- name: sysctl
  src: oefenweb.sysctl
  version: v1.0.43
- name: fqdn
  src: holms.fqdn
  version: "1.1"
