name: CI
on:
  - push
  - pull_request
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
        node_version:
          - 18
    name: Node ${{ matrix.node_version }} on ${{ matrix.os }}
    env:
      TRUTH_SOURCES: "truthsource.com"
      WEB_HOST: "example.com"
      SRS_SECRET: ${{ secrets.SRS_SECRET }}
      HELPER_ENCRYPTION_KEY: ${{ secrets.HELPER_ENCRYPTION_KEY }}
      PAYPAL_CLIENT_ID: ${{ secrets.PAYPAL_CLIENT_ID }}
      PAYPAL_ENHANCED_PLAN_180D: ${{ secrets.PAYPAL_ENHANCED_PLAN_180D }}
      PAYPAL_ENHANCED_PLAN_1Y: ${{ secrets.PAYPAL_ENHANCED_PLAN_1Y }}
      PAYPAL_ENHANCED_PLAN_30D: ${{ secrets.PAYPAL_ENHANCED_PLAN_30D }}
      PAYPAL_ENHANCED_PLAN_60D: ${{ secrets.PAYPAL_ENHANCED_PLAN_60D }}
      PAYPAL_ENHANCED_PLAN_90D: ${{ secrets.PAYPAL_ENHANCED_PLAN_90D }}
      PAYPAL_SECRET: ${{ secrets.PAYPAL_SECRET }}
      PAYPAL_TEAM_PLAN_180D: ${{ secrets.PAYPAL_TEAM_PLAN_180D }}
      PAYPAL_TEAM_PLAN_1Y: ${{ secrets.PAYPAL_TEAM_PLAN_1Y }}
      PAYPAL_TEAM_PLAN_30D: ${{ secrets.PAYPAL_TEAM_PLAN_30D }}
      PAYPAL_TEAM_PLAN_60D: ${{ secrets.PAYPAL_TEAM_PLAN_60D }}
      PAYPAL_TEAM_PLAN_90D: ${{ secrets.PAYPAL_TEAM_PLAN_90D }}
      PAYPAL_WEBHOOK_ID: ${{ secrets.PAYPAL_WEBHOOK_ID }}
      STRIPE_ENDPOINT_SECRET: ${{ secrets.STRIPE_ENDPOINT_SECRET }}
      STRIPE_PUBLISHABLE_KEY: ${{ secrets.STRIPE_PUBLISHABLE_KEY }}
      STRIPE_SECRET_KEY: ${{ secrets.STRIPE_SECRET_KEY }}
      AUTH_GOOGLE_ENABLED: "false"
      AUTH_GITHUB_ENABLED: "false"
      I18N_SYNC_FILES: "true"
      I18N_UPDATE_FILES: "true"
      TURNSTILE_ENABLED: "false"
      PREVIEW_EMAIL: "false"
    steps:
      - uses: actions/checkout@v4
      - name: setup node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node_version }}
      - name: start redis
        uses: supercharge/redis-github-action@1.4.0
        with:
          redis-version: latest
      - name: Install pnpm v7
        run: npm i -g pnpm@7
      - name: Install dependencies
        run: pnpm install
      - name: Run tests
        run: npm test
